### ISSUE TITLE
[FEAT] SignController 리팩토링

### ISSUE THREAD

**Issue by kikuke** [SSUDevelog/EasyVel-Server#1]
## Description
- SignController와 그와 관련된 기능 개발
- 중복 로직 제거, 에러 핸들링을 중점적으로 개발

## To-do
- [X] SignController 및 하위 코드 개발
- [X] 주요 설정 application.yml 이동
- [X] exception, security, jwt, swagger 개발
- [X] sign의 dto, url, 반환 값 변경
- [X] Swagger 편의성을 위한 어노테이션 EasyvelTokenApiImplicitParams 추가

## ETC
- 예상 마감: 2023/08/16 (화)
