### ISSUE TITLE
[FIX] 구독 관련 기능 QA 결과 반영

### ISSUE THREAD

**Issue by k0000k** [SSUDevelog/EasyVel-Server#32]
## Description
QA 에서 발견 된 구독 기능 오류들을 수정합니다.

## To-do
- [x] 구독 추가시 요청 형식에서 fcmToken을 삭제합니다.
- [x] 구독 추가에 유효성 검증 로직을 추가합니다.
- [x] 벨로그 유저 유효성 검사시 응답 형태가 잘못된것을 수정합니다.

## ETC
- 예상 마감:
