### ISSUE TITLE
[FIX] 쿼리스트링, 문서구조 변경 반영

### ISSUE THREAD

**Issue by kikuke** [SSUDevelog/EasyVel-Server#42]
## Description
- tag/delete 쿼리스트링 방식으로 변경 필요
- tags/search-posts와 tags/user-tag-posts API에서 '문서 구조가 변경되었습니다'

## To-do
- [x]  tag/delete도 위와 같이 쿼리스트링 방식
- [x]  tags/search-posts '문서 구조가 변경되었습니다'
- [x]  tags/user-tag-posts API '문서 구조가 변경되었습니다'

## ETC
- 예상 마감: 01/23
