### ISSUE TITLE
[FEAT] 무중단 배포를 위한 준비

### ISSUE THREAD

**Issue by sung-silver** [SSUDevelog/EasyVel-Server#9]
## Description

- 무중단 배포 환경을 구축하기 위한 API 를 개발하고 관련된 문제를 해결합니다

## To-do
- [x] application.yml 환경 분리
- [x] 인스턴스 내부 nginx 설치
- [x] deploy.sh, switch.sh 작성
- [x] nginx 설정파일 작성

## ETC
- 예상 마감: 9/12 (화)
